name: "Run black19.10b0 formatter"
description: "Run the black formatter on your codebase to improve code review experience."
author: "Rick Staa"
inputs:
  black_args:
    description: "Black input arguments."
    required: false
    default: ""
  fail_on_error:
    description: |
      Exit code when black formatting errors are found [true, false]. Defaults to 'true'.
    required: false
    default: "true"
  black_main_branch:
    description: |
      Main branch of the repository to speed up incremental diff
    required: false
    default: "main"
outputs:
  is_formatted:
    description: "Whether the files were formatted using the black formatter."
branding:
  color: "black"
  icon: "check-circle"
runs:
  using: "docker"
  image: "Dockerfile"